# Site wide configuration

title:            "Hi, iam Martin and I am a developer"
locale:           en_US
url:              http://martinhclausen.com/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true


# Site owner
owner:
  name: Martin Humlund Clausen
  avatar: bio-photo.jpg
  bio: "Entropy fighting codeslinger by day, Crossfitter by night"
  email: martinh.c@me.com
  disqus-shortname:
  twitter: martinhc
  facebook: #username
  google:
    plus: #username
    analytics: UA-71720086-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mclausen
  stackoverflow: 608966/martin-clausen
  linkedin: martinhc
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
